name: Cloud Resume Backend Package

run-name: Deploy to AWS by @${{ github.actor }}

on: push

jobs:
    run-tests:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
                python-version: ["3.11"]

        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install moto
                pip install boto3

            - name: Run tests
              run: pytest

    terraform_plan:
        needs: ['run-tests']

        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./

        permissions:
          id-token: write # This is required for requesting the JWT
          contents: read  # This is required for actions/checkout
        
        steps:
          - name: Git clone the repository
            uses: actions/checkout@v3

          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
              role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
              role-duration-seconds: 900
              aws-region: us-east-1

          - name: Use Terraform 1.5.7
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: 1.5.7
          
          # - name: Initialize Terraform
          #   run: terraform init

          - name: Terraform Plan api_resources
            run: |
              cd infrastructure/api_resources
              terraform init
              terraform plan
          
          - name: Terraform Plan iam_resources
            run: |
              cd infrastructure/iam_resources
              terraform init
              terraform plan
      
    terraform_apply:
      needs: ['run-tests','terraform_plan']

      runs-on: ubuntu-latest

      environment: 'dev'

      defaults:
        run:
          working-directory: ./

      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
      
      steps:
        - name: Git clone the repository
          uses: actions/checkout@v3

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            role-duration-seconds: 900
            aws-region: us-east-1

        - name: Use Terraform 1.5.7
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.7
        
        # - name: Initialize Terraform
        #   run: terraform init

        - name: Terraform Apply api_resources
          run: |
            cd infrastructure/api_resources
            terraform init
            terraform apply -auto-approve
        
        - name: Terraform Apply iam_resources
          run: |
            cd infrastructure/iam_resources
            terraform init
            terraform apply -auto-approve
        
        
    # terraform_api:
    #     needs: ['run-tests']

    #     runs-on: ubuntu-latest

    #     defaults:
    #       run:
    #         working-directory: ./

    #     permissions:
    #       id-token: write # This is required for requesting the JWT
    #       contents: read  # This is required for actions/checkout
       
    #     steps:
    #         - name: Git clone the repository
    #           uses: actions/checkout@v3

    #         - name: configure aws credentials
    #           uses: aws-actions/configure-aws-credentials@v3
    #           with:
    #             role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
    #             role-duration-seconds: 900
    #             aws-region: us-east-1

    #         - name: Use Terraform 1.5.7
    #           uses: hashicorp/setup-terraform@v2
    #           with:
    #             terraform_version: 1.5.7
            
    #         # - name: Initialize Terraform
    #         #   run: terraform init

    #         - name: Terraform Plan & Apply api_resources
    #           run: |
    #             cd infrastructure/api_resources
    #             terraform init
    #             terraform plan
    #             # terraform apply -auto-approve

    
    # terraform_iam:
    #   needs: ['run-tests']

    #   runs-on: ubuntu-latest

    #   defaults:
    #     run:
    #       working-directory: ./

    #   permissions:
    #     id-token: write # This is required for requesting the JWT
    #     contents: read  # This is required for actions/checkout
     
    #   steps:
    #       - name: Git clone the repository
    #         uses: actions/checkout@v3

    #       - name: configure aws credentials
    #         uses: aws-actions/configure-aws-credentials@v3
    #         with:
    #           role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
    #           role-duration-seconds: 900
    #           aws-region: us-east-1

    #       - name: Use Terraform 1.5.7
    #         uses: hashicorp/setup-terraform@v2
    #         with:
    #           terraform_version: 1.5.7

    #       - name: Terraform Plan & Apply iam_resources
    #         run: |
    #           cd infrastructure/iam_resources
    #           terraform init
    #           terraform plan
    #           # terraform apply -auto-approve



            
        
